---
title: "SocKult analysis"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(rstan)
library(rethinking)
library(stringr)
library(scales); library(ggthemes)
library(modelr)
source("../../Computational models/exercises/functions.R")
options(mc.cores = 4)

individual <- read.csv("data/individual.csv") %>% mutate(prop = k / n)
best_individual <- read.csv("data/best_individual.csv")
group <- read.csv("data/group.csv") %>% mutate(prop = k / n)
text <- read.csv("data/text_data.csv")
load("data/full.data.Rdata")
source("R/plate_notation.R")


# WAIC calculations

add_predictive_posterior <- function(dataset, model) {
    post <- extract.samples(model)
    dataset %>%
        mutate(theta_ind = purrr::pmap(list(group, intensity, vowel), function(gro,int,vow) {
            iA = post$ia + post$ia_vowel[,vow] + post$ia_group[,gro]
            iB = post$ib + post$ib_vowel[,vow] + post$ib_group[,gro]
            return(inv_logit(iA + iB * int))
        }), theta_gro = purrr::pmap(list(group, intensity, vowel), function(gro,int,vow) {
            gA = post$ga + post$ga_vowel[,vow] + post$ga_group[,gro]
            gB = post$gb + post$gb_vowel[,vow] + post$gb_group[,gro]
            return(inv_logit(gA + gB * int))
        }))
}

my_waic <- function(pred_post) {
    
    
    pred_post %>%
        mutate(
            lik_gro = purrr::pmap(list(k_gro, n_gro, theta_gro), function(k,n,theta){
                dbinom(k,n,theta, log=TRUE)}), 
            lik_ind = purrr::pmap(list(k_ind, n_ind, theta_ind), function(k,n,theta){
                dbinom(k,n,theta, log=TRUE)})) %>%
        # reshape both datasets to "one"
        gather("who", "ll", lik_gro, lik_ind) %>%
        mutate(
            lppd = purrr::map_dbl(ll, function(l) {
                n_samples = length(l)
                log_sum_exp(l) - log(n_samples)}),
            pwaic = purrr::map_dbl(ll, function(l) {
                var(l)})) %>%
        summarise(
            WAIC = -2 * (sum(lppd) - sum(pwaic)),
            WAIC_SE = sqrt(n() * 2 * var(-2 * (lppd - pwaic))),
            lppd = -2 * sum(lppd),
            pWAIC = sum(pwaic))
}


dataset = data_frame(
    n_gro = full.data$n_gro, 
    n_ind = full.data$n_ind, 
    k_gro = full.data$k_gro,
    k_ind = full.data$k_ind,
    group = full.data$group, 
    intensity = full.data$intensity, 
    vowel = full.data$vowel)

do_waic <- function(model, data = dataset) {
    
    tmp_ <- add_predictive_posterior(data, model) %>%
        my_waic()
    
    tryCatch({
        pos <- extract.samples(self_l)$col_b
    }, error = function(e) {
        try(pos <- extract.samples(self_l)$col_b1)
    })

    if (exists("pos")) {
        pri <- rnorm(length(pos))
        tmp_ <- tmp_ %>%
            mutate(BF01 = savage_dickey(pos, pri))
    }
    
    return(tmp_)
}
```

Stan code for the analysis of my Social and Cultural Dynamics exam


``` {r raw data plus model predictions, echo=F, fig.height=6, fig.width=8}
mutate(individual, who="Individual") %>%
    select(-participant) %>%
    rbind(mutate(group, who="Group")) %>%

    ggplot(aes(intensity, prop, colour=who)) +
    geom_line(stat="summary", fun.y=mean) +
    # geom_violin(aes(group = stringr::str_c(who, intensity, vowel)),  alpha=.2, position=position_identity(), scale = "width") +
    geom_jitter(aes(size=n), height=.05, width=.4, alpha=.2) +
    # geom_ribbon(stat="summary", fun.data=mean_cl_boot, alpha=.3) +
    facet_wrap(~ vowel) +
    labs(x = "Stimulus intensity (dB)", y = "Proportion correct answers",
         title = "Raw data (means per vowel per intensity)\nPoints are per participant\nLines are grand means") +
    guides(colour = guide_legend(title=element_blank())) +
    scale_size(range=c(1,4)) +
    theme_tufte() +
    scale_y_continuous(labels=percent) +
    scale_x_continuous(breaks = seq(5,26, 3)) +
    theme(axis.ticks.x = element_blank())

```

## Plate notation
```{r, echo=F, fig.width=12, fig.height=8}
plate
```



```{r comparing models}
model_list = data.frame(filename = list.files(path = "models/", pattern = "*.model")) %>%
    # .[1,] %>% data.frame(filename = .) %>%
    mutate(model = purrr::map_chr(filename, ~load(stringr::str_c("models/", .), envir = .GlobalEnv)))

waic_list <- model_list %>%
    mutate(WAIC = purrr::map(model, ~do_waic(get(.)))) %>%
    unnest() %>%
    arrange(WAIC) %>%
    mutate(dWAIC = WAIC - WAIC[1],
           weight = exp(-0.5 * dWAIC),
           weight = weight / sum(weight)
    ) %>%
    select(-filename) %>%
    # round the table to 3 digits
    mutate_at(vars(-model), function(co) {round(co, 3)}) %>%
    select(-BF01, -lppd)

# load("models/waic.Rdata")
waic_list
# save("waic_list", file="models/waic.Rdata")
# write.csv(waic_list, "models/waic_list.csv")
waic_list %>% mutate(model = str_replace_all(model, "_", " "),
                     model = str_replace_all(model, "and", "+")) %>%
    write.csv("models/waic_list.csv")
```



```{r, echo=F}
load("models/self_l_and_local_confidence.model")
post <- extract.samples(conf_align_local)
n_ <- length(post$collective_benefit)

post$collective_benefit %>%
    as_data_frame() %>%
    gather("Group") %>%
    mutate(Group = str_sub(Group, 2, 2)) %>%
    ggplot(aes(value, group=Group)) +
    geom_density() +
    labs(x = "Collective Benefit", y="",
         title = "Posteriors for collective benefit ~ Local Confidence Alignment\nEach line is a dyad") +
    theme_tufte() +
    theme(axis.text.y = element_blank(),
          axis.ticks.y = element_blank())#+
    # coord_cartesian(ylim=c(1.1, 20)) 

ggsave("plots/collective_benefit_3.png")


```





```{r}

pred.post.data <- extract.samples(self_entr) %>%
    as.data.frame() %>%
    as_data_frame() %>%
    select(col_b)

pred.post.data %>%
    gather() %>%
    mutate(wh = "posterior") %>%
    rbind(with(., data.frame(key = key,
                     value = rnorm(length(key)),
                     wh = rep("prior", length(key))))) %>%

    # group_by()
    ggplot(aes(value, fill=wh)) +
    geom_density(alpha=.4, colour=NA) +
    facet_wrap(~ key) #+
    # coord_cartesian(xlim = c(-0.2, 1.2))

# pairs(pred.post.data)
# pairs(self_l_x_cosine_conf_local_full, pars = c("col_a", "col_b1", "col_b2", "col_b3", "col_b4", "col_b5", "col_b6", "col_b7"))

```


```{r}
# confidence alignment back-scaling
# m = mean(text$local_alignment_confidence)
# s = sd(text$local_alignment_confidence)
# 
# data_frame(local_confidence = seq_range(full.data$local_confidence, 10)) %>%
#     mutate(samples = rep(list(pred.post.data), n()),
#            pred.post = purrr::map2(local_confidence, samples, ~.y$col_a + .y$col_b_confidence * .x),
#            local_confidence = (local_confidence * s) + m) %>%
#     unnest(pred.post) %>%
#     ggplot(aes(local_confidence, pred.post)) +
#     geom_line(stat="summary", fun.y=mean) +
#     geom_ribbon(stat="summary", fun.data=mean_hpdi, alpha=.3) +
#     geom_point(aes(local_confidence, y = .97), data = data.frame(local_confidence = (full.data$local_confidence * s) + m),
#                shape="|", size=3) +
#     theme_tufte() +
#     theme(axis.ticks = element_blank()) +
#     labs(x = "Local confidence alignment: Proportion of confidence expressions aligned with previous sentence",
#          y = "Predicted collective benefit, mean +- 89% HPDI",
#          title = "Counterfactual predictive posterior for explicit metacognition (confidence alignment)",
#          subtitle = "Actual dyads' confidence alignment as x-axis") +
#     scale_y_continuous(breaks = seq(.96,1.1, .02))

# ggsave("plots/pred_post_local_confidence.png")
```

```{r counterfactual predictive for the 3 way interaction model}

posterior = extract.samples(self_l_x_cosine_conf_local_full)

pred <- expand.grid(local_alignment_confidence = seq(-2,2,length.out = 10),
          self.l = seq(-2,2, 2),
          cosine_word_set = seq(-2,2,2)) %>%
    mutate(collective_benefit = purrr::pmap(list(local_alignment_confidence, self.l, cosine_word_set), function(loc, sel, cosi) {
        posterior$col_a +
            posterior$col_b1 * sel +
            posterior$col_b2 * loc +
            posterior$col_b3 * cosi + 
            posterior$col_b4 * loc * sel +
            posterior$col_b5 * cosi * sel +
            posterior$col_b6 * cosi * loc +
            posterior$col_b7 * cosi * loc * sel
    })) %>%
    plyr::adply(1, function(dat) {
        # print(dat)
        mean_hpdi(dat$collective_benefit[[1]])
    }) %>%
    select(-collective_benefit)



pred %>%
    ggplot(aes(local_alignment_confidence, ymin=ymin, y=y, ymax=ymax)) +
    geom_line() +
    geom_ribbon(alpha=.3) +
    theme_tufte() +
    theme(axis.ticks = element_blank()) +
    labs(x = "Local confidence alignment: Proportion of confidence expressions aligned with previous sentence (z-scale)",
         y = "Predicted collective benefit, mean +- 89% HPDI",
         title = "Counterfactual predictive posterior for the 3 way interaction model",
         subtitle = "Facets are z-scaled self L (chat predicability) and cos distance between word sets of interaction partners") +
    # scale_y_continuous(limits = c(0,1)) +
    coord_cartesian(ylim = c(0,6)) +
    facet_grid(cosine_word_set ~ self.l, labeller=label_both)

# ggsave("plots/3way_interaction.png")
```

```{r intercept model}
posterior = extract.samples(intercept)

pred <- data_frame(local_alignment_confidence = seq(-2,2,length.out = 10)) %>%
    mutate(collective_benefit = purrr::map(local_alignment_confidence, function(loc) {
        posterior$col_a
    })) %>%
    plyr::adply(1, function(dat) {
        # print(dat)
        mean_hpdi(dat$collective_benefit[[1]])
    }) %>%
    select(-collective_benefit)



pred %>%
    ggplot(aes(local_alignment_confidence, ymin=ymin, y=y, ymax=ymax)) +
    geom_line() +
    geom_ribbon(alpha=.3) +
    theme_tufte() +
    theme(axis.ticks = element_blank()) +
    labs(x = "Local confidence alignment: Proportion of confidence expressions aligned with previous sentence (z-scale)",
         y = "Predicted collective benefit, mean +- 89% HPDI",
         title = "Counterfactual predictive posterior for: intercept only model",
         subtitle = "Facets are z-scaled self L (chat predicability) and cos distance between word sets of interaction partners") +
    # scale_y_continuous(limits = c(0,1)) +
    coord_cartesian(ylim = c(.98,1.08))
```

```{r another model plot}
posterior = extract.samples(self_l_cosine_local_confidence)

pred <- expand.grid(local_alignment_confidence = seq(-2,2,length.out = 10),
          self.l = seq(-2,2, 2),
          cosine_word_set = seq(-2,2,2)) %>%
    mutate(collective_benefit = purrr::pmap(list(local_alignment_confidence, self.l, cosine_word_set), function(loc, sel, cosi) {
        posterior$col_a +
            posterior$col_b1 * sel +
            posterior$col_b2 * loc +
            posterior$col_b3 * cosi + 
            posterior$col_b4 * loc * sel +
            posterior$col_b5 * cosi * sel;
    })) %>%
    plyr::adply(1, function(dat) {
        # print(dat)
        mean_hpdi(dat$collective_benefit[[1]])
    }) %>%
    select(-collective_benefit)



pred %>%
    ggplot(aes(local_alignment_confidence, ymin=ymin, y=y, ymax=ymax)) +
    geom_line() +
    geom_ribbon(alpha=.3) +
    theme_tufte() +
    theme(axis.ticks = element_blank()) +
    labs(x = "Local confidence alignment: Proportion of confidence expressions aligned with previous sentence (z-scale)",
         y = "Predicted collective benefit, mean +- 89% HPDI",
         title = "Counterfactual predictive posterior for: self L * local + self L * cosine",
         subtitle = "Facets are z-scaled self L (chat predicability) and cos distance between word sets of interaction partners") +
    # scale_y_continuous(limits = c(0,1)) +
    coord_cartesian(ylim = c(0,3)) +
    facet_grid(self.l ~ cosine_word_set, labeller=label_both)
```

```{r a 3rd model plot}
posterior = extract.samples(conf_align_local)

pred <- data_frame(
        local_alignment_confidence = seq(-2,2,length.out = 10)
        # self.l = seq(-2,2, 2),
        # cosine_word_set = seq(-2,2,length.out=10)
        # self.l = 0,
        # local_alignment_confidence = 0,
        # cosine_word_set = 0
        ) %>%
    mutate(collective_benefit = purrr::map(local_alignment_confidence, function(loc) {
        posterior$col_a +
            posterior$col_b_confidence * loc
    })) %>%
    plyr::adply(1, function(dat) {
        # print(dat)
        mean_hpdi(dat$collective_benefit[[1]])
    }) %>%
    select(-collective_benefit)


pred %>%
    ggplot(aes(local_alignment_confidence, ymin=ymin, y=y, ymax=ymax)) +
    geom_line() +
    geom_ribbon(alpha=.3) +
    theme_tufte() +
    theme(axis.ticks = element_blank()) +
    labs(x = "Local confidence alignment: Proportion of confidence expressions aligned with previous sentence (z-scale)",
         y = "Predicted collective benefit, mean +- 89% HPDI",
         title = "Counterfactual predictive posterior for: local confidence alignment",
         subtitle = "Facets are z-scaled self L (chat predicability) and cos distance between word sets of interaction partners") +
    # scale_y_continuous(limits = c(0,1)) +
    coord_cartesian(ylim = c(.98,1.08))
    # facet_wrap(~ self.l, labeller=label_both)

```


```{r}

# gA = ga + ga_vowel[vowel] + ga_group[group]; 
# gB = gb + gb_vowel[vowel] + gb_group[group];
# gtheta[i] =  gA[i] + gB[i] * intensity[i];

# expand.grid(intensity = unique(full.data$intensity),
#             vowel = 1:4,
#             group = 1:9) %>%
#     mutate(Group = pmap(list(intensity, group, vowel), function(i,g,v){
#         post$ga + post$ga_vowel[,v] + post$ga_group[,g] +
#             (post$gb + post$gb_vowel[,v] + post$gb_group[,g]) * i
#     }), Individual = pmap(list(intensity, group, vowel), function(i,g,v){
#         post$ia + post$ia_vowel[,v] + post$ia_group[,g] +
#             (post$ib + post$ib_vowel[,v] + post$ib_group[,g]) * i
#     })) %>%
#     left_join(data.frame(group = 1:9, confidence = full.data$local_confidence)) %>%
#     gather("who", "theta", c(Group, Individual)) %>%
#     mutate(n = 10,
#            theta = purrr::map(theta, ~inv_logit(.))) %>%
#     mutate(vowel = c("e", "i", "o", "u")[vowel]) %>%
#     unnest(theta) %>%
#     ggplot(aes(intensity, theta, group=str_c(group, who), colour=confidence)) +
#     # geom_ribbon(aes(group=NA), stat="summary", fun.data=mean_hpdi, alpha=.3) +
#     geom_line(stat="summary", fun.y=mean, alpha=.7) +
#     geom_line(aes(group=NA), stat="summary", fun.y=mean, colour="red") +
#     facet_wrap(~ vowel, labeller = label_both) +
#     theme_few() +
#     labs(x = "Stimulus intensity (dB)", y = "Proportion correctly identified")

```


``` {r raw data plus model predictions, echo=F, fig.height=6, fig.width=8}

pred.plot.data <- dataset %>%
    data_grid(group = unique(group),
              intensity = unique(intensity),
              vowel = unique(vowel)) %>%
    add_predictive_posterior(conf_align_local) %>%
    gather("who", "pred", theta_ind, theta_gro) %>%
    mutate(who = ifelse(who == "theta_ind", "Individual", "Group")) %>%
    group_by(intensity, vowel, who) %>%
    summarise(pred = list(unlist(pred))) %>%
    mutate(hp = purrr::map(pred, ~mean_hpdi(.))) %>%
    unnest(hp) %>%
    ungroup() %>%
    mutate(vowel = c("e", "i", "o", "u")[vowel])


mutate(individual, who="Individual") %>%
    select(-participant) %>%
    rbind(mutate(group, who="Group")) %>%

    ggplot(aes(intensity, prop, colour=who)) +
    geom_line(aes(ymin=ymin,y=y,ymax=ymax, colour=who), data=pred.plot.data) +
    # geom_jitter(aes(size=n), height=.01, width=.4, alpha=.2) +
    geom_point(aes(group = str_c(group), size=n), position=position_jitterdodge(jitter.height=.05, dodge.width = 3, jitter.width=0)) +
    geom_ribbon(aes(ymin=ymin,y=y,ymax=ymax, fill=who), data=pred.plot.data, colour=NA, alpha=.1) +
    # geom_ribbon(stat="summary", fun.data=mean_cl_boot, alpha=.3) +
    # geom_violin(aes(group=group.intensity)) +
    facet_wrap(~ vowel) +
    labs(x = "Stimulus intensity (dB)", y = "Proportion correct answers",
         title = "Model predictions", subtitle="Line and shaded areas are average across groups (mean +- 89% HPDI)\nRaw data: One point per participant per vowel per intensity\nCollective benefit ~ Local Confidence Alignment") +
    guides(colour = guide_legend(title=element_blank()),
           fill = guide_legend(title=element_blank())) +
    scale_size(range=c(1,4)) +
    theme_tufte() +
    scale_y_continuous(labels=percent) +
    scale_x_continuous(breaks = seq(5,26, 3)) +
    theme(axis.ticks.x = element_blank())

ggsave("plots/raw_pred_local_conf_alignment.png")
```


```{r different kind of predictive plot}
load("models/self_l.model")
post <- extract.samples(self_l)
expand.grid(self_l = seq(-3, 3, 3)) %>%
    mutate(collective_benefit = purrr::map(self_l, function(par) {
        mu = post$col_a + post$col_b * par
        rnorm(length(mu), mu, post$collective_sigma)
    })) %>%
    unnest() %>%
    mutate(self_l = factor(self_l)) %>%
    ggplot(aes(collective_benefit, colour=self_l)) +
    geom_density() +
    # facet_grid(self_l ~ ., labeller=label_both) +
    coord_cartesian(xlim = c(.8, 1.25)) +
    # guides(colour = guide_legend(title = element_blank())) +
    labs(x = "Collective Benefit", y = "Predictive posterior",
         title = "Predictive posterior for collective benefit in one of the simpler models\ncollective benefit ~ chat similarity + local confidence alignment")
    
# ggsave("plots/pred_coll_self_l_local_conf.png")


## next level
preddata <- dataset %>%
    data_grid(group = unique(group),
              intensity = unique(intensity),
              vowel = unique(vowel))





plotdata2 <- expand.grid(self_l = seq(-3,3,3),
            intensity = unique(individual$intensity),
            group = 1:9,
            vowel = 1:4) %>%
    mutate(collective_benefit = purrr::map(self_l, function(par) {
        mu = post$col_a + post$col_b * par
        rnorm(length(mu), mu, post$collective_sigma)
    })) %>%
    mutate(theta_ind = purrr::pmap(list(group, intensity, vowel), function(gro,int,vow, coll) {
               
                iA = post$ia + post$ia_vowel[,vow] + post$ia_group[,gro]
                iB = post$ib + post$ib_vowel[,vow] + post$ib_group[,gro]
                return(inv_logit(iA + iB * int))
                }), 
           theta_gro = purrr::pmap(list(group, intensity, vowel, collective_benefit), function(gro,int,vow, coll) {
                gA = post$ga# + post$ga_vowel[,vow] + post$ga_group[,gro]
                
                gb_group_theta = inv_logit(post$ib + post$ib_vowel[,vow] + post$ib_group[,gro]) * coll
                gb_group = logit(gb_group_theta) - (post$gb + post$gb_vowel[,vow])
                
                gB = post$gb + gb_group + post$gb_vowel[,vow]
                return(inv_logit(gA + gB * int))
                })) %>%
    gather("who", "pred", theta_ind, theta_gro) %>%
    mutate(who = ifelse(who == "theta_ind", "Individual", "Group")) %>%
    group_by(intensity, who, self_l) %>%
    summarise(pred = list(unlist(pred))) %>%
    mutate(hp = purrr::map(pred, ~median_hpdi(., prob=.5))) 


plotdata2 %>%
    # unnest(hp) %>%
    unnest(pred) %>%
    ungroup() %>%
    filter(complete.cases(pred)) %>%
    mutate(self_l = factor(self_l, labels = c("Low self-consistency L (-3 SD)", "Mean self-consistency", "High self-consistency L (+3 SD)"))) %>%
    ggplot(aes(intensity, colour = who, fill = who, group = stringr::str_c(who, intensity))) +
    # geom_line(aes(y=y)) +
    # geom_ribbon(aes(ymin=ymin, ymax=ymax), alpha=.2, colour=NA) +
    geom_violin(aes(y=pred), alpha=.3, position = position_identity(), scale = "width") +
    facet_grid(self_l ~ .) +
    labs(x = "Intensity (dB)", y = "Proportion correct answers",
         title = "Predictive posterior density\ncollective_benefit ~ self l + local conf align") +
    guides(fill = guide_legend(title = element_blank()),
           colour = guide_legend(title = element_blank()))
    

# ggsave("plots/pred_post_self_l.png")
```

```{r intercept advanced plot}
load("models/intercept.model")
post <- extract.samples(intercept)
preddata <- dataset %>%
    data_grid(group = unique(group),
              intensity = unique(intensity),
              vowel = unique(vowel))





plotdata2 <- expand.grid(intensity = unique(individual$intensity),
            group = 1:9,
            vowel = 1:4) %>%
    mutate(collective_benefit = purrr::map(1:nrow(.), function(i) {
        mu = post$col_a
        rnorm(length(mu), mu, post$collective_sigma)
    })) %>%
    mutate(theta_ind = purrr::pmap(list(group, intensity, vowel), function(gro,int,vow, coll) {
               
                iA = post$ia + post$ia_vowel[,vow] + post$ia_group[,gro]
                iB = post$ib + post$ib_vowel[,vow] + post$ib_group[,gro]
                return(inv_logit(iA + iB * int))
                }), 
           theta_gro = purrr::pmap(list(group, intensity, vowel, collective_benefit), function(gro,int,vow, coll) {
                gA = post$ga# + post$ga_vowel[,vow] + post$ga_group[,gro]
                
                gb_group_theta = inv_logit(post$ib + post$ib_vowel[,vow] + post$ib_group[,gro]) * coll
                gb_group = logit(gb_group_theta) - (post$gb + post$gb_vowel[,vow])
                
                gB = post$gb + gb_group + post$gb_vowel[,vow]
                return(inv_logit(gA + gB * int))
                })) %>%
    gather("who", "pred", theta_ind, theta_gro) %>%
    mutate(who = ifelse(who == "theta_ind", "Individual", "Group")) %>%
    group_by(intensity, who) %>%
    summarise(pred = list(unlist(pred))) %>%
    mutate(hp = purrr::map(pred, ~median_hpdi(., prob=.5))) 


plotdata2 %>%
    # unnest(hp) %>%
    unnest(pred) %>%
    ungroup() %>%
    filter(complete.cases(pred)) %>%
    mutate(intensity = factor(intensity)) %>%
    ggplot(aes(intensity, colour = who, fill = who, group = stringr::str_c(who, intensity))) +
    # geom_line(aes(y=y)) +
    # geom_ribbon(aes(ymin=ymin, ymax=ymax), alpha=.2, colour=NA) +
    geom_violin(aes(y=pred), alpha=.3, position = position_identity(), scale = "width") +
    # facet_grid(self_l ~ local_confidence_alignment, labeller = label_both) +
    labs(x = "Intensity (dB)", y = "Proportion correct answers",
         title = "Predictive posterior density\nNull Model (intercept only)") +
    guides(fill = guide_legend(title = element_blank()),
           colour = guide_legend(title = element_blank())) +
    scale_y_continuous(labels = percent)
```





```{r pred plot 444043}
# load("models/conf_align_local.model")
# post <- extract.samples(conf_align_local)
# expand.grid(par = seq(-3, 3, 3)) %>%
#     mutate(collective_benefit = purrr::map(par, function(par) {
#         mu = post$col_a + post$col_b * par
#         rnorm(length(mu), mu, post$collective_sigma)
#     })) %>%
#     unnest() %>%
#     mutate(par = factor(par)) %>%
#     ggplot(aes(collective_benefit, colour=par)) +
#     geom_density() +
#     # facet_grid(self_l ~ ., labeller=label_both) +
#     coord_cartesian(xlim = c(.8, 1.25)) +
#     # guides(colour = guide_legend(title = element_blank())) +
#     labs(x = "Collective Benefit", y = "Predictive posterior",
#          title = "Predictive posterior for collective benefit in one of the simpler models\ncollective benefit ~ chat similarity + local confidence alignment")
    
# ggsave("plots/pred_coll_self_l_local_conf.png")


## next level


# ggsave("plots/pred_post_self_l.png")
```
# comparing the four models from optimally interacting ..


```{r predictive posteriors plots for all}

```


```{r coefficient table}
model_list %>%
    filter(!model %in% c("intercept")) %>%
    # filter(model == "align_l") %>%
    plyr::adply(1, function(ro) {
        beta = extract.samples(get(ro$model))$col_b
        hp = map_hpdi(beta, prob=.95)
        # try(plot_predictive(get(ro$model), ro$model))
        
        data_frame(Estimate = hp$y,
                   `Lower 95%` = hp$ymin,
                   `Upper 95%` = hp$ymax)
    }) %>% select(-filename) %>%
    arrange(desc(Estimate)) %>%
    mutate_at(vars(-model), function(co) {round(co, 4)}) %>%
    write.csv("models/estimate_table.csv")
    
```



# Coin flip model
# (s1 + s2) / 2
# Behaviour and feedback model
# max(s1, s2)
# weighted confidence sharing
# (s1 + s2) / (2 ^ 1/2)
# direct signal sharing
# (s1 ^ 2 + s2 ^ 2) ^ 1/2



```{r}
# bayes factor



```

    
